const customer = {
  name: "Test Customer",
  company: "Test Residence",
  email: "customer@example.test",
  phone: "+91 9000000000",
  address: "Test site, Pune",
  type: "residential",
};
const finance = {
  capacity: 5,
  genFactor: 1400,
  costPerKwp: 50000,
  gstPercent: 0,
  tariff: 8,
  exportTariff: 0,
  selfConsumption: 100,
  escalation: 0,
  degradation: 0,
  annualOm: 0,
  years: 25,
  subsidy: 0,
  payAdvance: 0,
  payDispatch: 90,
  payCompletion: 10,
  customerType: "residential",
  subsidyEligibility: "not-applicable",
  subsidySource: "",
  assumptions:
    "TEST FIXTURE ONLY. Explicit fixed yield and zero tax/escalation/O&M, full self consumption. Not project evidence.",
};
const engineering = {
  moduleCount: 12,
  wp: 500,
  voc: 50,
  vmp: 40,
  isc: 12,
  imp: 11,
  tempCoeffVoc: -0.25,
  tempCoeffVmp: -0.3,
  tempCoeffIsc: 0.05,
  minCellTemp: -10,
  maxCellTemp: 70,
  mpptMin: 150,
  mpptMax: 600,
  maxDCVoltage: 650,
  mpptCount: 2,
  inputsPerMppt: 2,
  maxCurrentPerMppt: 32,
  maxIscPerMppt: 40,
  acKw: 5,
  maxDcKw: 8,
  currentSafetyFactor: 1.25,
};
const proposal = (customerId) => ({
  title: "Test rooftop solar offer",
  customerId,
  finance: { ...finance },
  engineering: {},
  scope: "Supply and installation as agreed.",
  exclusions: "Grid fees; financing; replacements.",
  terms: "Site survey and engineer approval required before installation.",
  companyPhone: "+91 9000000001",
  companyEmail: "ktm@example.test",
  validUntil: "2030-12-31",
});
module.exports = { customer, finance, engineering, proposal };
